Switch input RSE file
Don't need to load SummarizedExperiment if we are loading SingleCellExperiment since SCE depends on SE. See http://bioconductor.org/packages/release/bioc/html/SingleCellExperiment.html. By depending instead of importing, it means that it gets loaded too (and makes the functions available to users).

Switch from tidyverse to loading dplyr + tidyr. Helps avoid loading issues in some scenarios (when you have loaded some packages via ~/.Rprofile). See for example:

```R
master* > library("tidyverse")
── Attaching packages ──────────────────────────────────────── tidyverse 1.3.1 ──
✔ ggplot2 3.3.6     ✔ purrr   0.3.4
✔ tibble  3.1.7     ✔ dplyr   1.0.9
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1
Error: package or namespace load failed for ‘tidyverse’:
 .onAttach failed in attachNamespace() for 'tidyverse', details:
  call: value[[3L]](cond)
  error: Package ‘tibble’ version 3.1.6 cannot be unloaded:
 Error in unloadNamespace(package) : namespace ‘tibble’ is imported by ‘tidyr’, ‘modelr’, ‘haven’, ‘ggplot2’, ‘styler’, ‘dplyr’, ‘readr’, ‘dbplyr’, ‘broom’, ‘googledrive’ so cannot be unloaded
```

Remove session info since it'll be on the log file